### ISSUE TITLE
JSON.parse of JavaScript object crashes build

### ISSUE THREAD

**Issue by paularmstrong** [TylorS/typed-content-hash#10] opened 2021-02-05 00:08 UTC
Offending line is here: https://github.com/TylorS/typed-content-hash/blame/5bd7c081d83e5850e28f78bb81403d8f5add7a6b/src/content-hashes/infrastructure/fsWriteDocuments.ts#L27

It appears that `JSON.parse(document.contents)`, when `document.contents` is an object, the build crashes. Removing the `JSON.parse` fixes my build.

Let me know if there's any other information you need.

```
(node:22804) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.<anonymous> /project/node_modules/@typed/content-hash/lib/content-hashes/infrastructure/fsWriteDocuments.js:21:34)
    at Generator.next (<anonymous>)
    at /Users/paularms/development/frigate/web/node_modules/@typed/fp/cjs/Effect/toEnv.js:10:57
    at Object.value /project/node_modules/@typed/fp/cjs/Effect/ap.js:16:59)
    at effectGeneratorToResume /project/node_modules/@typed/fp/cjs/Effect/toEnv.js:16:35)
    at /Users/paularms/development/frigate/web/node_modules/@typed/fp/cjs/Effect/toEnv.js:10:12
    at Object.value /project/node_modules/@typed/fp/cjs/Effect/ap.js:16:49)
    at effectGeneratorToResume /project/node_modules/@typed/fp/cjs/Effect/toEnv.js:16:35)
    at /Users/paularms/development/frigate/web/node_modules/@typed/fp/cjs/Effect/toEnv.js:18:47
    at /Users/paularms/development/frigate/web/node_modules/@typed/fp/cjs/Resume/chain.js:11:84
    at Object.run /project/node_modules/@typed/fp/cjs/Resume/run.js:7:59)
    at /Users/paularms/development/frigate/web/node_modules/@typed/fp/cjs/Resume/chain.js:11:80
    at onValue /project/node_modules/@typed/fp/cjs/Resume/ap.js:24:20)
    at /Users/paularms/development/frigate/web/node_modules/@typed/fp/cjs/Resume/ap.js:28:20
    at Object.run /project/node_modules/@typed/fp/cjs/Resume/run.js:7:59)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22804) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22804) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by TylorS** [comment] 2021-02-05 15:56
Hello @paularmstrong 👋 thanks for opening an issue. Sorry your build is breaking! 

This is quite unexpected actually. If you look at the type for `Document.contents` [here](https://github.com/TylorS/typed-content-hash/blob/development/src/content-hashes/domain/model.ts#L6), you'll see it should _always_ be a string. Would you be able to `JSON.stringify(document.contents)` there when it is an object? I'm curious if it's already a RawSourceMap or something else - and then I need to track down how that's getting through the types 🤔

**Comment by paularmstrong** [comment] 2021-02-05 15:59
I'm using this in your `snowpack-plugin-hash` (latest version as of yesterday). Here's my config, thankfully it's pretty short:

```js
'use strict';

module.exports = {
  mount: {
    public: { url: '/', static: true },
    src: { url: '/dist' },
  },
  plugins: [
    '@snowpack/plugin-postcss',
    '@prefresh/snowpack',
    'snowpack-plugin-hash',
  ],
  routes: [{ match: 'routes', src: '.*', dest: '/index.html' }],
  packageOptions: {
    sourcemap: false,
  },
  buildOptions: {
    sourcemap: true,
  },
};
```

Did some debugging, and here is `document.contents`: https://gist.github.com/paularmstrong/1da6b36f5d0fe37c94955cd422e8e54a

Looks like it's hitting the `index.css` that's generated by postcss, so here's that config as well:

postcss.config.js
```js
'use strict';

module.exports = {
  plugins: [
    require('tailwindcss'),
    require('autoprefixer'),
  ],
};
```

tailwind.config.js
```
'use strict';

module.exports = {
  purge: ['./public/**/*.html', './src/**/*.jsx'],
  darkMode: 'class',
  theme: {
    extend: {
      screens: {
        '2xl': '1536px',
        '3xl': '1720px',
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
```

Or, if you want the project: https://github.com/paularmstrong/frigate/tree/snowpack-plugin-hash/web (note branch name), cd to the `web` directory and `npm i && npm run build`

**Comment by TylorS** [comment] 2021-02-05 16:07
It's so refreshing that snowpack configs tend to be pretty simple 😄 

There's a configuration for snowpack-plugin-hash of `registryFile: string` that could be useful for use here. If you could set it to something like `document-registry.json`, and re-run a build with your fix in place, it should write a JSON file with all of the documents this library found and processed. If you could post that back here it might help point me in the right direction as well, thanks!

**Comment by paularmstrong** [comment] 2021-02-05 16:10
Ah sorry, updated the comment above. I added that to the config and I don't see a file written at all

**Comment by TylorS** [comment] 2021-02-05 16:23
Interesting! Something odd is happening for sure. 

Thanks for the github repo for reproduction though, that will really help. I should be able to investigate soon

**Comment by TylorS** [comment] 2021-02-05 17:49
Hey @paularmstrong, thanks again for the github repo it made it alot quicker to find the source of the errors! 

It turns out I had a redundant `JSON.parse` (which returns "any") when creating the new sourceMap was safely being assigned to `document.contents`. I had managed to skate by this bug because the library the does remapping of sourceMaps accepts both strings and `RawSourceMap`s, but in the case where we are generating a _new_ sourceMap it would break when trying to write. 

`v0.8.3` here and `v0.14.2` for `snowpack-plugin-hash` should fix this error.

**Comment by paularmstrong** [comment] 2021-02-05 17:50
Awesome thank you!!

**Closed as completed** 2021-02-05 17:49 UTC
